name: spatial-analysis
channels:
-   conda-forge
dependencies:
-   python=3.8
-   pip
-   pip:
    -   squidpy>=1.0.0
    -   spatial-utils
    -   esda>=2.3.1
    -   libpysal>=4.3.0
    -   astropy>=4.1
    -   numba==0.52.0